"""Create_a_baseline_migrations

Revision ID: e7c9fdb2c9cf
Revises: 
Create Date: 2024-06-21 22:54:25.889267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c9fdb2c9cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('base', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cryptos_id'), 'cryptos', ['id'], unique=False)
    op.create_index(op.f('ix_cryptos_name'), 'cryptos', ['name'], unique=False)
    op.create_index(op.f('ix_cryptos_symbol'), 'cryptos', ['symbol'], unique=False)
    op.create_table('klines1m',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crypto_id', sa.Integer(), nullable=True),
    sa.Column('open_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('open_dateTime', sa.DateTime(), nullable=True),
    sa.Column('open_price', sa.String(length=100), nullable=True),
    sa.Column('high_price', sa.String(length=100), nullable=True),
    sa.Column('low_price', sa.String(length=100), nullable=True),
    sa.Column('close_price', sa.String(length=100), nullable=True),
    sa.Column('volume', sa.String(), nullable=True),
    sa.Column('close_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('close_price_dateTime', sa.DateTime(), nullable=True),
    sa.Column('quote_asset_volume', sa.String(), nullable=True),
    sa.Column('number_of_trades', sa.Integer(), nullable=True),
    sa.Column('taker_buy_base_asset_volume', sa.String(), nullable=True),
    sa.Column('taker_buy_quote_asset_volume', sa.String(), nullable=True),
    sa.Column('pourcent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['crypto_id'], ['cryptos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_klines1m_crypto_id'), 'klines1m', ['crypto_id'], unique=False)
    op.create_index(op.f('ix_klines1m_id'), 'klines1m', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_klines1m_id'), table_name='klines1m')
    op.drop_index(op.f('ix_klines1m_crypto_id'), table_name='klines1m')
    op.drop_table('klines1m')
    op.drop_index(op.f('ix_cryptos_symbol'), table_name='cryptos')
    op.drop_index(op.f('ix_cryptos_name'), table_name='cryptos')
    op.drop_index(op.f('ix_cryptos_id'), table_name='cryptos')
    op.drop_table('cryptos')
    # ### end Alembic commands ###
